### ISSUE TITLE
Specify html responses

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/OGC-API-Tiles#10]
As discussed in https://github.com/opengeospatial/OGC-API-Tiles/issues/3#issuecomment-586104872 one of the major improvements of OGC API's from the web best practices is to have an html page for everything. Though I don't think we want to over-specify exactly what an html response should look like I think we should call it out as an output type for the 'tiles description' object.

**Comment by joanma747** [comment]
Review what features api does and provide some examples to illustrate the value of html response.

**Comment by ghobona** [comment]
Included a Permission for HTML in this PR https://github.com/opengeospatial/OGC-API-Tiles/pull/33

The relevant Commit is https://github.com/opengeospatial/OGC-API-Tiles/pull/33/commits/9c10618607ca9ae3186347120917f5709fde86e8

**Comment by ghobona** [comment]
The SWG approved the PR https://github.com/opengeospatial/OGC-API-Tiles/pull/33 today.
