### ISSUE TITLE
Allow title and description on /tiles response object

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/OGC-API-Tiles#12]
The current 'tiles description' object at /tile only has tilematrixsets and links in the example, and the fields available aren't listed. It looks like there's implementations, as mentioned in https://github.com/opengeospatial/OGC-API-Tiles/issues/3#issuecomment-585868603 that use these fields. I see a strong use case for them, and would be good to include them in the spec.

**Comment by joanma747** [comment]
Particularly useful in the HMTL case. We could encourage the server implementors to reuse other titles. Backlinks (rel=parent) to the collection level could be useful.

**Comment by ghobona** [comment]
@cholmes The title and description are now included in the example. Please see the attached screenshot. I presume that @joanma747 has already updated the example.

![Screenshot 2020-06-01 at 19 33 45](https://user-images.githubusercontent.com/18121038/83441732-ec715780-a43e-11ea-8457-7955ece26ccd.png)

**Comment by joanma747** [comment]
this is done; and much more in the TileSetMetadata
