### ISSUE TITLE
conformance class URIs

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/OGC-API-Tiles#20]
Requirement 27 in section 7.4.1 seems to specify that the conformance class URI for the core requirements class is "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core".  However, that's a requirements class URI, not a conformance class URI.  The conformance class URI should be "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core".

The same is true for Requirement 41 in section 8.3.1.

Example 6 (Conformance Information Page fragment) should therefore be:

```
  {
    "conformsTo": [
      "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
      "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/collections",
      "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core"
      "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/collections"
    ]
  }
```

**Comment by ghobona** [comment]
Fixed by PR https://github.com/opengeospatial/OGC-API-Tiles/pull/24
