### ISSUE TITLE
Maintaining normative independence from closed specifications (non-SDO specs)

### ISSUE THREAD

**Issue by cnreediii** [opengeospatial/OGC-API-Tiles#29]
Much of the work in recent OGC initiatives has made use of formats and specifications that are publicly accessible but are developed in closed processes by organizations that are not Standards Development Organizations (SDOs). OGC API - Tiles should not have a dependency on a closed specification, even if that specification is publicly accessible. The issue is that an OGC normative document cannot express normative requirements (or recommendations) that state the use of some document (spec) that is not an official standard. For example the Tiles API cannot have any normative references that are dependent on TileJSON nor MVT. The Tiles API can have a non-normative extension that states how to use TileJSON or MVT.

**Comment by ghobona** [comment]
The SWG will discuss the following relevant Pull Request https://github.com/opengeospatial/OGC-API-Tiles/pull/33 on Thursday 28 May.

**Comment by ghobona** [comment]
The SWG approved PR https://github.com/opengeospatial/OGC-API-Tiles/pull/33 today and the changes were merged into the master branch.
