### ISSUE TITLE
tile template as a first class object instead of a 'link'

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/OGC-API-Tiles#3]
The use of a URL Template in the main 'link' of the [tiles description](https://github.com/opengeospatial/OGC-API-Tiles/blob/master/standard/clause_7_tile_core.adoc#tiles-description) object feels a bit weird, as I'd expect links to be something that a browser can resolve, not a template that needs to be filled in. 

It also seems to be the most important piece of information communicated in the tiles description response, so we should consider emphasizing it a bit more. 

```
"tile-templates": [
    {
     "url-template": "http://data.example.com/collections/buildings/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.png",
     "type": "image/png",
   }
   ...
  ]
```

It seems like it should be a list so you can have multiple templates - like for png and jpeg (unless there's another way to do that?), and for alternate visualizations, like false color bands or an alternate style. Would likely be good to add (optional) title and description, so that clients can display the options and then use them as the layer name.

```
"tile-templates": [
    {
     "title": "Building Tiles (png)"
     "description": "A visualization of the Building collection ..."
     "url-template": "http://data.example.com/collections/buildings/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.png",
     "type": "image/png",
   }
   ...
  ]
```

**Comment by cportele** [comment]
When we discussed the options for representing URI templates according to RFC 6570 in the [Vector Tiles Pilot](https://www.opengeospatial.org/projects/initiatives/vt-pilot-2018) we came to the conclusion that it would be best to use a link object and add support for expressing this using an additional JSON member to express that the link is not a "clickable link", but a URI template. We followed the approach taken by HAL and added a boolean-valued `templated` member that defaults to `false` ([HAL](https://tools.ietf.org/html/draft-kelly-json-hal-00#section-5.2), [Vector Tiles Pilot Report](http://docs.opengeospatial.org/per/18-078.html#direct_access_path)). 

I still think that this is a good approach and what all OGC API Tiles implementations that I have accessed over the last year (e.g. ldproxy, GeoServer, Ecere, CubeWerx) do.

I cannot find `templated` in the current OGC API Tiles draft though. If that is the case, it is missing and should be added.

**Comment by cholmes** [comment]
That seems more reasonable than how the draft reads now. @cportele - what was the rel you used for the link? Right now it's `"rel": "item"`, which seems pretty weird to me.

**Comment by cportele** [comment]
As a general rule, if there is a registered link relation where the semantic fits, it makes sense to reuse it instead inventing something new.

In the Vector Tiles Pilot we used `tiles` (see the link to the report), but this was later changed to `item`. 

In my view, `item` would make sense, if the resource would not be a "tiles description", but a single "tile set". Then each link (after inserting the template parameters) would link to an item in the tile set/collection. 

But as it is right now, the semantics does not work, I agree:

* To me "tiles description" is incorrect, the resource is not just metadata (even though most of the content in the document that you get back is metadata). The resource represents one or more "tile sets", the tiles are all sub-resources of the resource.
* And since it is multiple tile sets (multiple collections) and not a single tile set, `item` does not work; the relationship between the collections and the individual tiles is unclear.

**Comment by cholmes** [comment]
Is ‘item’ a registered link relation outside of oafeat? It feels to me like
a very non-descriptive relation, seems better to me to give some context to
what this thing is. Why did you change from ‘tiles’? That does seem more
appropriate to me.

I’m not sure I 100% follow what you are proposing - could you share a
sample? Ideally one with multiple tile sets. I’m particularly interested in
one that is represented as both vector tiles and png tiles, and alternate
representations- like footprints of imagery vs actual imagery. I struggled
with the current spec on what those would look like.

Also curious how a GUI would represent different tile set options, I
suppose use the “title” attribute on link?

I’d be happy to make a pr if we can align.

**Comment by cportele** [comment]
Yes, `item` is registered: https://www.iana.org/assignments/link-relations/link-relations.xml

Here is a discussion about the link relation types used in OGC API Features: http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_link_relations. This issue in OGC API Common is relevant in this context, too. I don't think that "tiles" would have a chance to get registered by IANA, maybe something more specific like "map-tile-template" would have a chance.

I don't have an example with bitmaps, but here is a resource that in my view represents 6 tile sets (3 different tile matrix sets, 2 different encodings):

* the JSON: https://services.interactive-instruments.de/t15/daraa/collections/TransportationGroundCrv/tiles?f=json
* and that's how ldproxy currently represents it in HTML (just using the MVT tiles, this is work-in-progress): https://services.interactive-instruments.de/t15/daraa/collections/TransportationGroundCrv/tiles?f=html

**Comment by cholmes** [comment]
Ah, cool - those links makes more sense to me. There's a number of interesting bits in there that don't seem captured in the spec, that seem worth their own issues:

* Title and Description - I see a strong use for these, have been discussing implementing the spec with @notthatbreezy @geospatial-jeff and @tschaub and title and description seemed quite useful. 

* Title on links - one example in the ogc-api tiles spec has this, but doesn't really explain it. We were consider title + description at the tile-template / item level, to help drive a GUI, but perhaps the link title do double duty. Though your message in the link text that it's a URL is less useful for driving a GUI.
 
* Inline `tileMatrixSetLinks` - I didn't see this as an option in the spec, the examples just had objects with tileMatrixSet and tileMatrixSetURI. Is what you did valid? I didn't see it in a quick scan of the vector tiles pilot, but may have missed it. I find it interesting as an option - I do want to consider defaults that implements don't have to specify, as in #4. But if we do want to be explicit then it could be decent if verbose way to have people include the defaults. One thing I do like in this is that you are communicating valid zoom levels. TileJSON has the option to do that, and seems pretty valuable, though theirs is simpler.

* I don't really understand your `items` link. My guess would be that would be to navigate down in the hierarchy, but I tried https://services.interactive-instruments.de/t15/daraa/collections/TransportationGroundCrv/tiles/WebMercatorQuad and that didn't work. It also seems less useful for navigation if you have to put the link in. Curious what the value of that link is.

* I *love* the html rendering. Does seem valuable to have the spec talk about that a bit more explicitly, as that to me is the big change with the new round of OGC API's. One minor thing, I think it'd be a lot cleaner to just show one map with 3 buttons for the three projections/tilematrices.

**Comment by cportele** [comment]
> Inline tileMatrixSetLinks - I didn't see this as an option in the spec, the examples just had objects with tileMatrixSet and tileMatrixSetURI. Is what you did valid? 

I think it is valid. 

The spec is sometimes inconsistent and requires more work. For example, it is unclear to me why `tileMatrixSetLimits` is mentioned in the text of the Core conformance class, but only defined in the Tile Matrix Set conformance class.

I do not know, what the plan is to move the draft forward, not much has happened recently. The [OGC API roadmap](http://www.ogcapi.org/apiroadmap.html) seems to indicate that it should be published as a standard in autumn, but that seems unrealistic. @joanma747?

> I don't really understand your items link. My guess would be that would be to navigate down in the hierarchy, but I tried https://services.interactive-instruments.de/t15/daraa/collections/TransportationGroundCrv/tiles/WebMercatorQuad and that didn't work. It also seems less useful for navigation if you have to put the link in. Curious what the value of that link is.

This is just a link to the definition of each Tile Matrix Set. For the well-known tile matrix sets, in particular WebMercatorQuad, this will not be used (just like noone resolves the URIs of the well-known CRSs), but for custom tile matrix sets clients will need to access it. 

Thanks for pointing out that there is a bug, the link should resolve. I guess this shows that the link is not used for the well-known sets. The response should be the same as https://services.interactive-instruments.de/t15/daraa/tileMatrixSets/WebMercatorQuad. We will fix that.

I do not remember why `rel=items` is used. This does not make sense to me now, there must have been a discussion in Testbed-15. Looking at the draft spec I couldn't find information about the link relation type to use.

> I love the html rendering. Does seem valuable to have the spec talk about that a bit more explicitly, as that to me is the big change with the new round of OGC API's.

Yes, in my view usable HTML is an important aspect of the OGC APIs, although it is challenging from a spec perspective as it is difficult/impossible to have detailed testable requirements for the HTML representations of the resources. I think this is one area where implementations will differ.

That said, this is one area where the current draft is lacking. It does not discuss requirements for encodings of the resources and in my view there need to be conformance classes for encodings like MVT, HTML, etc.

> One minor thing, I think it'd be a lot cleaner to just show one map with 3 buttons for the three projections/tilematrices.

I agree (imagine there would be 20 tile matrix sets supported!). We just didn't have the time yet to change the implementation in that way.

**Comment by cholmes** [comment]
> I do not know, what the plan is to move the draft forward, not much has happened recently. The OGC API roadmap seems to indicate that it should be published as a standard in autumn, but that seems unrealistic. @joanma747?

I'm happy to contribute a decent bit of time to help, as I've got more standards time at work right now, and believe this is the most important specification for OGC API to get right. Happy to start making PR's after issues are discussed on the way forward. I'd just really focus on the core as documented in the readme. Though will probably need some help on translating into the requirement stuff.

I'll spin a couple issues out of this discussion.

**Comment by cholmes** [comment]
@cportele - as I'm making issues, I don't quite get the point you made above:

> And since it is multiple tile sets (multiple collections) and not a single tile set, item does not work; the relationship between the collections and the individual tiles is unclear.

What are you saying here? Is this true if we rename the object to 'tile set' from 'tile description'? As in #11? It looks like in your response you have two 'item' links, each with different types.

**Comment by cportele** [comment]
@cholmes - 

If we use the 'tile set' term from the [OGC Two Dimensional Tile Matrix Set standard](http://docs.opengeospatial.org/is/17-083r2/17-083r2.html) ("a series of actual tiles contain data and following a common tiling scheme") the resource at https://services.interactive-instruments.de/t15/daraa/collections/TransportationGroundCrv/tiles?f=json represents six tile sets with the data in the collection. There are three different tiling schemes (one based on CRS84 one one based on Mercator in addition to the standard one) and two formats (MVT and GeoJSON) that are supported. 

We could also consider this as three tile sets, one for each tiling scheme. In the web architecture, the tile is still a single resource, whether I fetch it in the MVT or GeoJSON representation. But users of a static tile cache will probably have a different view.

In any case, the resource should probably be called 'tile sets'.
