### ISSUE TITLE
Add Conformance Class and Requirements on supporting Multi-layer Tiles

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/OGC-API-Tiles#30]
There is a need to be able to support a single tile with multiple feature types.

Please refer to the Vector Tiles Pilot Phase 2 reports for an example of how this works.

**Comment by jerstlouis** [comment]
I suggest that this conformance class should be part of OGC API - Common (Part 2: Collections).

Because one could get the exact same result on a single layer/collection, (multi-layer) collection, or single-dataset OGC API end-point with multiple layers with:
- Tiles
- BBOX (clipping box) + resolution

**Comment by jeffharrison** [comment]
Thanks for adding this issue Gobe. I agree there is a need to be able to support a single tile with multiple feature types.

And yes, solutions have been built and successfully demonstrated as part of the recent Vector Tiles Pilot, Phase 2. 

Best Regards,
Jeff

**Comment by joanma747** [comment]
Here we are talking about a tile that represents one geospatial resource that is a predefined combination of other things (e.g. feature types) and you want to inform what things are inside the tiles. To do that we only need to be able to retrieve the list of "things" of the tiles (among other metadata) as tilejson. There is already a path to get the description of the tiles:  
{geopsatialresource}/tiles
In normal circumstances it will return something like the example in here:
https://app.swaggerhub.com/apis/UAB-CREAF/ogc-api-tiles-opf-xmp-vt-more-1-collection/1.0.0#/Tiles%20metadata/describeTiles

Here is my proposal: Use the media type negociation in the request (e.g. application/tile+json) and get a tilejson back in the same endpoing. If the  {geospatialresource} is a /collection/{collectionId], it will probably return only one featuretype in the list but if the {geospatialresource} is the root, will work like the Clemens implementation, and it will be compatible with what was proposed here: 
https://app.swaggerhub.com/apis/UAB-CREAF/ogc-api-tiles-opf-xmp-vt-more-1-collection/1.0.0#/Tiles%20metadata/describeTilesCollections
If the {geospatialresource} is a collection of a collection it will work like Jerone's implementation (without the /metadata; but this is just a detail).

**Comment by cportele** [comment]
@joanma747 - That does not work for two reasons:

* `{resource}/tiles` represents 1..n tile sets (multiple tile encodings, multiple tiling schemes), but each TileJSON document describes exactly one tile set. These are different resource types.
* Both resource types do not have registered media types, so the media type is `application/json` for both.

**Comment by jerstlouis** [comment]
@cportele The TMS aspect of your first point we discussed in the call today, that /tiles/{tileMatrixSetId} would be where the TileJSON is found for a specific TMS. About multiple encodings, did the /metadata approach used in VTP2 allow multiple tile encodings?

The second point we also discussed would be addressed by defining a different media type as Joan suggested (application/tile+json, though what the proper media type should be would need to be discussed).

In general, I think relying solely on 'type' to differentiate things is problematic (especially with media types as generic as JSON).
An example I brought up before is our GNOSIS Map Tiles which could contain very different things (e.g. raster, vector or even 3D data). 

Is there general W3C guidance on this? Adding an additional property to those 'links'?
This issue is presenting itself in many places.

**Comment by cportele** [comment]
@jerstlouis - In VTP2 we ignored the encoding aspect as it was all about MVT, but a proper solution will need another path or query parameter for the encoding, I think.

I don't really see `/tiles/{tileMatrixSetId}` returning TileJSON, which I think is the result of the unresolved disagreement about the resource types. The current draft calls `/tiles` the "tiles description" resource, where for me it is a "tile sets" resource. Yes, if you ask for `application/json` you will get some JSON with links to everything that is contained in the tile sets. But if you would ask for a media type that represents a tiles set in a single file you would get that back from the `/tiles/{tileMatrixSetId}` and not some other sub-resource. This resource is by-the-way also the resource used by the multi-tiles extension, so there is another conflict.

Regarding a media type registration for TileJSON: I thought the decision was for OGC not to register a media type with IANA for third-party specs? 

On the architectural aspects: HTTP and Web Linking is defined by IETF and we really should play by the Web rules and avoid inventing new OGC conventions. W3C has worked on a spec for Content Negotiation by Profile which goes in that direction, so you may want to take a look, but whatever we do must still work for clients / developers that only understand the IETF conventions.

**Comment by jerstlouis** [comment]
> a proper solution will need another path or query parameter for the encoding, I think.
I guess a query parameter on the TileJSON could link to another encoding? (while the native Tiles API "tiles description" way can always feature more than one link to encodings). 

>  where for me it is a "tile sets" resource
Do you mean potentially more than one, unrelated tile sets?

For me, /tiles provides whatever comes before it according to the TMS standard.
So you would need separate resources above to differentiate unrelated tile sets.
In my view "tiles" are not a fundamental type of data, they are an implementation detail for achieving performance (caching, focusing on an AOI...). e.g. you could be serving features, coverage or 3D data using the Tiles API, but fundamentally, it is not "tiles" that you are serving. Tiles is just one way to partition, store and disseminate that data. BBOX+resolution is another, DGGS is another, subsetting (as used in coverages) is another.

> This resource is by-the-way also the resource used by the multi-tiles extension, so there is another conflict.
I did not realize that, but I think the multi-tiles extension might have been put to the side as I think it was agreed that the current approach was not particularly useful.
So far we have used this /tiles/{tileMatrixSetId} in our implementation to return the same as /tiles, but limited to a single TMS. This avoids a very long list of TMSLinks and limits if the server supports a very large number of TMSes.

**Comment by joanma747** [comment]
One way of avoiding the Media type issue could be to use a solution already present in other standards (I remember it in CSW and in WPS): To separate format and schema. It was used in XML but there is no reason for not to do it in JSON.

So:
format: application/json
schema: tilejson

This could be done with a "f" parameter and an "s" parameter or by content negotiation (with schema negotiation). 

I agree with Jerome that the multitile extension is not being accepted by many and it will have to wait. So let's get this one done first and then we will see what we will do with the multitile problem. We might end up needing a "package" building block

**Comment by jerstlouis** [comment]
@joanma747 This is along the lines what I was suggesting and asking what the guidance is from web principles. Even a schema I think is not enough for some cases to precisely describe what something is (e.g. a GeoPackage with the data as vector tiles, or the data as map tiles).

@cportele is referencing two things:
- IETF Web linking ( https://tools.ietf.org/html/rfc8288 )
In particular this has a provision for "2.2 Target Attributes" https://tools.ietf.org/html/rfc8288#section-2.2
"Target attributes are a list of key/value pairs that describe the link or its target; for example, a media type hint."
This is exactly the kind of thing we need, so I think it would be fair to standardize a practice of using this in the OGC API, for richer description of what you will get at a link?
- W3C Profile Negotiation ( https://www.w3.org/TR/dx-prof-conneg/ )
https://www.w3.org/TR/dx-prof-conneg/#listprofiles (list profiles) and https://www.w3.org/TR/dx-prof-conneg/#getresourcebyprofile (get resource by profile) also seems relevant.

**Comment by ghobona** [comment]
Completed with PR https://github.com/opengeospatial/OGC-API-Tiles/pull/32, following SWG decision on 2020-05-28.
