### ISSUE TITLE
Tile Matrix Default to WebMercator in Core

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/OGC-API-Tiles#4]
I was very excited to see a goal in the readme was 'Only support for WebMercatorQuad'. But on reading the core I saw no indication that it was constrained in that way.

The one example in the doc has 'WorldMercatorWGS84Quad', not 'WebMercatorQuad'.

I'd also expect it to not need the tileMatrixSetLinks unless I was using something other than WebMercatorQuad. But they seem to be required. I think it'd be ideal if a user could read the core and not be exposed to that at all - if your using the default WebMercatorQuad then I think the template should be able to hard code it:

```
{
  "links": [
    ...
    {
     "href": "http://data.example.com/collections/buildings/tiles/WebMercatorQuad/{tileMatrix}/{tileRow}/{tileCol}.png",
     "rel": "item",
     "type": "image/png",
   }
   ...
  ]
}
```
The core spec should just explain the tiling scheme of WebMercatorQuad, and that implementors need to include that in their response. Then when they read a next spec that explains the tile matrices they'll understand that it's hardcoded in the core, but that it's actually a flexible construct.

**Comment by ghobona** [comment]
WebMercatorQuad is supported, but the API is not constrained to it.

One of the reasons for not constraining the API to WebMercatorQuad is that it would alienate a large part of the D&I community. See the slides from the D&I DWG session of the 2015 TC meeting in Boulder.

**Comment by cholmes** [comment]
I don't see it as 'constraining the API', it's just providing a reasonable default - the one that is most commonly used by far. D&I has always been quite comfortable with profiles of OGC, indeed they most always make their own profiles. 

The whole tilematrix thing is a lot of cognitive overhead for a first time user of the specification. It'd be really nice to just not have to specify it, and that assumption would mean it's web mercator. I'd even be ok with specifying the additional 8 (though would argue should slim it down a bit) in the core, but it helps developer a lot to have one clear target to try to do first.

**Comment by jeffharrison** [comment]
We (and other agencies) have a requirement for TMS that are Not Web Mercator, specifically 4326 and 3395 (at the very least).

Best Regards,
Jeff

**Comment by ghobona** [comment]
@cholmes Thanks for the clarification.

I will ask the SWG to consider adding a mechanism for a default TMS that would be Web Mercator. Other TMS would also continue to be supported. 

There's a SWG telecon this Thursday 28 May.

**Comment by cholmes** [comment]
Great. And slimming to 4326 and 3395 from the 8 would also be great. 

It'd also be good to explicitly tell people exactly what they need to do to use one of them. Like do you use the OGC's explicit schema? Is the client expecting to actually resolve that? Or can it just count on those being stable, and if they see http://schemas.opengis.net/tms/1.0/json/examples/WorldMercatorWGS84Quad.json can they just make an assumption? 

Could consider making the URL optional if it's one of the 'known' ones, or to use some alternative notation. Like somehow be able to just say WorldMercatorWGS84Quad

**Comment by jeffharrison** [comment]
Well, there are also the two polar stereographic TMS needed...  can't remember the codes off the top of my head.

Best Regards,
Jeff

**Comment by mcechini** [comment]
We use EPSG:3031 and EPSG:3413 ... however, our TMS was built historically off of the data we were visualizing.  Same for EPSG:4326.  So, supporting a specific projection may not actually matter if the TMS is not "generic" for all who would use it.

**Comment by cholmes** [comment]
Polar seems pretty 'niche' to me - I'd not have them in the 'pre-sets' that have default names in the core spec. But they could be 'named extensions' or something that have published tilematrices that everyone can use, and then of course should work well with the general framework (which is true for any CRS).

**Comment by jeffharrison** [comment]
Gobe has outlined a practical way forward on this IMHO...

Ask the SWG to consider adding a mechanism for a default TMS that would be Web Mercator. Other (8) TMS would also continue to be supported.

**Comment by jeffharrison** [comment]
I rescind my previous comment. This topic needs additional review by a larger section of the community.

Best Regards,
Jeff

**Comment by ghobona** [comment]
@cholmes Concerns have been raised about the options for TMS.

To allow for further discussion, I will not proceed with the proposal tomorrow.

**Comment by jeffharrison** [comment]
FYI we have proposed a potential way forward to OGC Staff. 

We can review it tomorrow with the SWG at the telecon.

Best Regards,
Jeff

**Comment by cholmes** [comment]
What's the proposal? I'm unable to attend the telecon. It'd be great if we could just hash out the issue here, so people in the future can see how this was decided.

**Comment by jeffharrison** [comment]
Let me see what I can do. It might take me until tomorrow morning...

**Comment by cholmes** [comment]
Cool. Totally fine if it's shared here after the meeting, just would be great to have the visibility.

**Comment by jeffharrison** [comment]
Deal!  (and thank goodness for the Tiles API development and testing OGC members did in the Vector Tiles Pilot ;-)

**Comment by ghobona** [comment]
The SWG passed the following motion today (2020-05-28) to update the draft specification as follows.

_TileMatrixSetLink is made mandatory as part of the response of a ‘tiles’ description, and clients or servers are not required to support a specific default TileMatrixSet. An example of implementing this approach will be provided close to the relevant requirement (currently /req/tiles/core/sct-tmxslink)._

_A recommendation would be included for use of the tile matrix sets described in Annex D and H of the 2D TMS standard (OGC 17-083r2)._

There was no objection to unanimous consent.

OGC members can access the [text of the motion](https://portal.ogc.org/files/?artifact_id=93371) and the [recording of the meeting](https://portal.ogc.org/files/?artifact_id=93370) on the OGC Portal.

With the passing of the motion, this GitHub issue will now be closed.

**Comment by cholmes** [comment]
Ok, I just spent 20 minutes watching the video, and I am so confused. 

Everything seemed to be going great. @jeffharrison's proposal looked awesome, requirement 26 is already written, and seems totally compatible with the proposal. I think supporting the D&I community that sponsored the testbed makes perfect sense, and the idea of having 4 more common matrices described in the core sounds good to me - it shows how this spec can do 'more' than TileJSON, etc. Issue solved!

And then somehow the conclusion was to revert all of that? I had assumed that my issue raised was just to point out that one of the 'goals' articulated in the readme wasn't quite lining up with the reality. That goal was one of the ones that made me most excited about that specification. And 
I apologize I wasn't able to attend the meeting to articulate why this is important (it's at 7am and I have to take care of my 2 year old then). But let me try here:

Having a default of the most commonly used commercial projection enables a developer who has been tasked to implement a tile server to come to the standard and get their job done without having to understand what a projection is. The support for projections is obviously one of the most powerful things in the Tiles API, but it is also the most confusing. By making a default we ease the cognitive load of approaching a new specification, so someone doesn't need to deeply understand geospatial to get started. If there wasn't a clear default then this would be a harder decision, but there is one. I will note that I believe the default should not be *required* - if an AGC server and clients only want to support the official D&I standard projections then great! They can use the same core and their 'profile' of it will require that the tms returned is one of their acceptable ones. I had really thought a goal of the OGC API evolution was to make things more accessible to people outside the existing geospatial world. We have the opportunity to ease the onramp into geospatial, but this decision to me appears to go directly in the opposite direction. And we'll lose an opportunity to have people start with a standard that has real *depth* behind it - instead they'll go to TileJSON or write their own, and we'll have *less* interoperability. People wanting a 'quick' tile server will go that route, and those who need 'more' and are willing to spend the time will use OGC API - Tiles. So things split, instead of meeting the needs of the 'simple' users at the same time as the more complex uses (which is how things stand today - use TileJSON if you need to bang out something quick, use WMTS if you need it to talk to ESRI desktop).

I don't understand the argument the other way, except from a 'purity' standpoint - that every projection should be treated equally, and that people should know their projection. But it would be great if someone could better articulate the advantage of not having a default. I believe there are ways to address all the concerns brought up by Jeff - non-required default if you leave it blank, include the 4 main alternatives in the core as common ones to use. I love that approach, as it then naturally links to the TMS specification where people can learn more about geospatial and projections. 

Is there a way to reopen the issue? Is the decision final? It'll make me sad if this is the final decision, and if things continue to go in the 'anti-general dev' / 'geospatial expertise required' direction then it'll be hard for me to promote this to the communities I'm a part of.

**Comment by cportele** [comment]
After the comment from @cholmes I have listened to the first 30 minutes of the recording, too. +1 from me to what @cholmes says.

It is important to support developers that are not geospatial experts. This is what has driven the mandatory default CRS in OGC API Features and I think OGC API Tiles would benefit from recognizing the status of WebMercatorQuad as the de-facto convention. At the same time, for all the reasons mentioned by @jeffharrison, it makes perfect sense to not require that an API must support WebMercatorQuad (in that sense, this would be more lax than the CRS requirements in OGC API Features), but a default would still make sense to make OGC API Tiles suitable for all the uses that do not care about anything else but WebMercatorQuad.

My proposal would have been:

* Make WebMercatorQuad the default and providing details about the use of WebMercatorQuad optional.
* Recommend to be explicit with the TMS link and limits also in the WebMercatorQuad case.
* Recommend to consider the use of any of the TMS in the TMS standard annex as long as one of the TMS is fit for purpose for the intended use of the tile set.

Sorry, I couldn't attend the call due to a conflict with another call.

**Comment by ghobona** [comment]
@cholmes  The TC [PnPs](http://docs.opengeospatial.org/pol/05-020r27/05-020r27.html#withdrawal) allow for a Motion to be withdrawn by the SWG that made the original motion. Since the motion in question has already been executed (i.e. the changes have already been made), I think the proposal in Comment https://github.com/opengeospatial/OGC-API-Tiles/issues/4#issuecomment-637346403 would be a new Motion. So either way, the issue can be reopened.

**Comment by jeffharrison** [comment]
Thanks very much for the kind words. Our proposal is what I briefed, and I am happy to see the issue reopen.

I am glad folks think our proposal makes sense.

Best Regards,
Jeff
