### ISSUE TITLE
Suggest a starting point for navigating the tiles in the tiles description

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-API-Tiles#48]
TileJSON includes a tile center:

>// OPTIONAL. Default: null.
// The first value is the longitude, the second is latitude (both in
// WGS:84 values), the third value is the zoom level as an integer.
// Longitude and latitude MUST be within the specified bounds.
// The zoom level MUST be between minzoom and maxzoom.
// Implementations can use this value to set the default location. If the
// value is null, implementations may use their own algorithm for
// determining a default location.
"center": [ -76.275329586789, 39.153492567373, 8 ]

Can we include this to have a nice way to start in the tile descriptions .
For TMS "zoom level" is selecting one of the TileMatrix ID.

opengeospatial/OGC-API-Tiles#31 (Has OGC considered Center Point?)

**Comment by mcechini** [comment]
It's not clear to me what is being requested here...  When this came up in the email discussion, I thought it was more in the context of request vs definition.  So a user could request a map (or tiles) given a center point.  But if we're considering adding center point to the definition of the TileSet ... I'm not sure how useful that is.  That's a pretty simple calculation given the TileMatrixSet definition. Same would go for the center point of any given tile in that TileMatrixSet too.

**Comment by jeffharrison** [comment]
FYI, when we brought this up the original idea was that a user could request a map (or tiles) given a center point. 

Best Regards,
Jeff

**Comment by joanma747** [comment]
IT is considered as part ofTileSetMetadata. Please see: https://github.com/opengeospatial/OGC-API-Tiles/issues/47
