### ISSUE TITLE
Please chnage the name in the quick guide

### ISSUE THREAD

**Issue by cnreediii** [opengeospatial/OGC-API-Tiles#53]
I know I am being a "harpie", but if any OGC document content is not specifically related to MapBox vector tiles, then we (OGC) must use a neutral term such as "tiled data" or "tiled vector data" that does not suggest to the reader that we are speaking of a particular product (aka MapBox Vector Tiles).

**Comment by jeffharrison** [comment]
Carl,

Do you have a reference link?

Thanks and Regards,
Jeff

**Comment by jeffharrison** [comment]
Also, Mapbox Vector Tiles doesn't usually refer to a 'product'. It usually refers to the specification...

Regards,
Jeff

**Comment by mcechini** [comment]
Big +1 on removing all specific references to "vector tiles" in the specification/quick start/wherever.  The current tiles spec uses the "vector tiles" term in lots of places that should instead be a generic "map tiles" or something similar.

**Comment by jeffharrison** [comment]
I'm pretty sure we've covered this about a dozen times in OGC already, and I think the position is (was) to use the term 'tiled feature data'...

Best Regards,
Jeff

**Comment by cnreediii** [comment]
OAB Hat on. Sorry, but there is a broader consistency issue then just vector or feature data. There could be tiled imagery, tiled coverages, tiled 3D models (such as in CDB), tiled LiDAR, tiled whatever. And tiling is relevant to other dimensions beyond 2D. As such, the OGC should be consistent in this terminology across all emerging API and other standards.

**Comment by jeffharrison** [comment]
Carl,

That's fine. When we've discussed this previously, I believe folks were ok with the term 'tiled feature data'. Has something changed since we sponsored the Vector Tiles Pilots?

Thanks and Regards,
Jeff

**Comment by cnreediii** [comment]
Takes me back to the OGC days when some argued that everything is a feature! Others argued that an observation is not a feature and that a coverage is not a feature. I am not sure that argument ever was resolved to anyone's satisfaction. Anyway, in CDB there are objects that are tiled that are not features - at least in terms of the ISO definition. From an abstract viewpoint, anything that covers space can be partitioned (as with MBBs) or tiled (as in TMS).

**Comment by jeffharrison** [comment]
Well, certainly nobody's suggesting everything be called 'tiled feature data'. You've got tiled coverage data, tiles whatever data out there. Honestly, I have no idea why OGC finds this concept so hard to communicate ;-)

Regards,
Jeff

**Comment by ghobona** [comment]
@cnreediii 

The User Guide is an educational or informative document rather than a normative specification. 

One precedent for this is [CDB Volume 4](https://portal.opengeospatial.org/files/16-070r3), which is an OGC Best Practice, is called "OGC CDB Best Practice use of Shapefiles for Vector Data Storage" and talks about use of Esri Shapefiles in CDB data stores.

**Comment by jeffharrison** [comment]
@ghobona Given that OGC CDB uses non-vendor-neutral terms in an 'official position' paper of the OGC Membership, then use of the term Mapbox Vector Tiles should be fine in the User Guide.

Best Regards,
Jeff

**Comment by cnreediii** [comment]
@jeffharrison - Perhaps the confusion is that the Quick Guide is for requesting content from a feature collection in a tiled store. The Quick Guide is not for specifically accessing a MapBox structured store. There could definitely be an OGC Best Practice on using MapBox technology or structured content with one or more OGC standards. In that BP case, the term "vector tiles" is just fine. Best Practice documents are good OGC documents to speak to such technology or more vendor specific approaches.

**Comment by jeffharrison** [comment]
@cnreediii I don't see any confusion. The point is that if OGC can have an entire 'official position' in the form of a Best Practice that talks about Esri Shapefiles, then it can say the words Mapbox Vector Tiles in a Quick Guide.

Hopefully OGC doesn't have one set of policies for one set of folks and another set for other folks.

Regards,
Jeff

**Comment by cnreediii** [comment]
@jeffharrison WRT OGC Best Practices, we are saying the same thing! The issue is that the quick guide is not MapBox specific! The quick guide is for any developer/user who wishes to use the OGC API - Tiles to get content from a feature collection that has been tiled. As such, the terminology and wording should reflect this.

**Comment by jeffharrison** [comment]
@cnreediii Please point me to the approved OGC policy that says editors may mention vendor specific technology in Best Practices and not in User Guides. Otherwise, it seems like this is, well, just your opinion.

Regards,
Jeff

**Comment by cnreediii** [comment]
@jeffharrison - Of course products can be mentioned in User Guides. However, I think you are missing my point. The particular User Guide being referenced here is OGC API - Tiles and not about MapBox  but about using the OGC API - Tiles draft spec. So my recommendation is to change the title and so forth so as to not indicate a particular product or technology. The OGC API - Tiles is geospatial technology/product agnostic - which is a very good thing!

**Comment by jeffharrison** [comment]
@cnreediii I believe you may be missing my points. OGC user guides often mention technology. Which is fine. In addition, OGC specifications have informative references. Which is also fine. User guides for OGC specifications also mention technology (more frequently than you might think). Also fine.

I think the bottom line to this issue is that the Mapbox specification should be fine to reference as long as it is informative. The user guide is an informative document rather than a normative specification.

Regards,
Jeff

**Comment by chris-little** [comment]
@jeffharrison, @cnreediii  I think this confusion arises from the fact that until a few weeks ago, there was no such thing as an OGC "Quick Guide", only Best Practice documents. In the EDR API SWG we agreed to produce a BP of developing/using/maintaining/etc an EDR API for meteorology. One for, say, geology, may be different, even though the API would be identical. HTH.

**Comment by geospatial-jeff** [comment]
As an OGC outsider I'm not super familiar with best practices, but "vector tiles" really has nothing to do with Mapbox Vector Tiles (.mbtiles) to begin with.  The former is a general concept for serving vector data to a client while the latter is a particular implementation of this concept.

A quick search for the term "vector tiles" on google brings up many results which aren't related to mapbox, here are a few:
- Geoserver uses "vector tiles" terminology (https://docs.geoserver.org/latest/en/user/extensions/vectortiles/tutorial.html)
- Leaflet has several plugins to display "vector tiles" (https://leafletjs.com/plugins.html#vector-tiles)
- OSM has this entire page on "vector tiles" which only mentions mapbox once (https://wiki.openstreetmap.org/wiki/Vector_tiles#:~:text=Vector%20tiles%20are%20a%20way,the%20features%20in%20the%20tile.)

Vector tiles is the most widely used and understood terminology in the community, and using a different term that is less familiar only muddies the water which kind of defeats the purpose of a quick guide.

**Comment by jeffharrison** [comment]
@geospatial-jeff  Well said -> 'Vector tiles is the most widely used and understood terminology in the community, and using a different term that is less familiar only muddies the water which kind of defeats the purpose of a quick guide.'

**Comment by joanma747** [comment]
I believe there is no consensus on this issue. I propose to simply close it.
