### ISSUE TITLE
Formalize Vector Layer Definition

### ISSUE THREAD

**Issue by mcechini** [opengeospatial/OGC-API-Tiles#55]
There are a couple existing schemas for defining the contents of a vector tile:

1. [Mapbox TileJSON 3.0.0](https://github.com/mapbox/tilejson-spec/blob/3.0/3.0.0/schema.json)
2. VTP Phase 2 Results [Tile Set Metadata Engineering Report](http://docs.opengeospatial.org/per/19-082r1.html) / [Summary Engineering Report](http://docs.ogc.org/per/19-088r2.html) 

There was some discussion in [issue 43](https://github.com/opengeospatial/OGC-API-Tiles/issues/43#issuecomment-663338836) regarding a `vector_layers` field... but perhaps it'd be good to extract that discussion into an issue of its own.  

I believe the current suggestion is to add the `vector_layers` field to the `collections/{collection_id}/tiles/{tileset_id}` resources as is seen in [this](http://maps.ecere.com/ogcapi/collections/Daraa/tiles/WebMercatorQuad?f=tilejson) example.

**Comment by joanma747** [comment]
Redundant with https://github.com/opengeospatial/OGC-API-Tiles#43 and dealt with in https://github.com/opengeospatial/2D-Tile-Matrix-Set/issues/11
