### ISSUE TITLE
Clarify internal resolution of vector tiles

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/OGC-API-Tiles#59]
The MapBox Vector Tile specification (https://github.com/mapbox/vector-tile-spec/tree/master/2.1), or rather its protobuf schema, suggests an "extent" of 4096 units for each tile.  If this were to be used for the standard 256x256 tiles that "OGC API - Tiles" servers tend to serve, that would imply 16x oversampling in each dimension.  The justification for such oversampling, as I understand it, is to provide enough resolution for a client to zoom in by up to four zoom levels without having to fetch more tiles.

But does this make any sense in the context of "OGC API - Tiles"?  If a client wants this extra resolution, couldn't it just request the tiles at the appropriate zoom level to begin with?  Why make each tile 16x (or even 8x, 4x or 2x) larger than necessary for the zoom level they're being requested for?  It's a colossal waste of generation time, disk space, bandwidth and transfer time.  Wouldn't it be better for nominally-256x256 MVT tiles served by "OGC API - Tiles" servers to have an "extent" of 256 units?

Also, I assume that this logically applies to GeoJSON vector tiles as well.  GeoJSON vector tiles don't use integerized internal coordinates like MVT tiles do, but the vectors within them are still simplified to a particular resolution.  Like with MVT tiles, I'm wondering if there's any point in simplifying them to a finer resolution than the nominal resolution of the tile.

Perhaps the "OGC API - Tiles" specification should provide some guidance on this matter.

**Comment by jeffharrison** [comment]
@pomakis I don't think we want to make tiles any larger than necessary. And for capabilities such as offline caching we want to make them as small as possible... whether they are integerized internal coordinates like MVT or feature geometries like GeoJSON.

I do wonder whether the change you suggest would somehow break existing client applications (?)

Best Regards,
Jeff

**Comment by pomakis** [comment]
I'm not suggesting a change; more requesting clarification and suggesting that such clarification (or recommendation) be added to the specification.

It seems common practice (?) for MVT tiles to be generated with an internal extent of 4096x4096.  Should that common practice carry over to "OGC API - Tiles", or should "OGC API - Tiles" recommend that the internal extent match the nominal pixel resolution of that tile as indicated by the tile-matrix set (usually 256x256).  The latter makes more sense to me, but I'm relatively new to the vector-tile world so I may be missing something.

Client applications that accept MVT tiles should be able to accept them with any reasonable internal extent, so there should be no issue there either way.  For example, the MVT tiles currently generated by CubeWerx have an internal extent of 4x the nominal pixel resolution (so typically 1024x1024), and I'm not aware of any client application having a problem with that.  But our pregenerated cache of these tiles takes a long time to generate and takes up a lot of disk space, and I'm wondering if all of this extra resource utilization is unnecessary.

**Comment by joanma747** [comment]
The consensus in the 2020-10-29 meeting is to avoid restrictions on this. We can mention that sometimes there is need for more precisions. The quantization of coordinates to a grid creates imperfections that can be solved by having a more dense grid (because vector tiles are not rasterized; only quantized)
