### ISSUE TITLE
More clarity on tile types - vector, png, jpeg, etc

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/OGC-API-Tiles#9]
The specification has very little to say on vector vs raster tiles, when you might use each, and even what the 'type' to use for each is. There's likely a good discussion to be had in a 'best practices' paper about when to use each format, what their advantages + disadvantages are. But in the core spec it does seem like there should at least be some 'common tile types', with their mime-type listed, and perhaps a bit more information on each. I'd recommend some minimal set that all servers should support, but could also go features api route and not have a default, but they do at least specify 3 types clearly.

**Comment by joanma747** [comment]
In the notes of the discussion in 2019 Toulouse meeting there was a discussion on "Add extensions on formats and mime types". I'm not so sure this is a good idea: it might prevent people to use future formats (in particular new forms of vector tiles). It need to be an extension and it needs to be clear that formats can be used without any extensions. (In OWS Context defining extensions for formats demonstrated an unnecessary limitation)

**Comment by cholmes** [comment]
Sorry, I'm not sure what you're suggesting as the way forward?

**Comment by ghobona** [comment]
Some example formats are mentioned in https://github.com/opengeospatial/OGC-API-Tiles/blob/master/core/standard/clause_7_tile_core.adoc

The SWG will discuss the following relevant Pull Request on Thursday 28 May.

https://github.com/opengeospatial/OGC-API-Tiles/pull/33

**Comment by ghobona** [comment]
The SWG approved PR https://github.com/opengeospatial/OGC-API-Tiles/pull/33 today.
